### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by valours** [boogie666/atom-mocha#8]
[Enter steps to reproduce below:]
1. Install package
2. Run tests

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-mocha](https://github.com/boogie666/atom-mocha) package, v0.0.4
### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /Users/valentin/.atom/packages/atom-mocha/lib/atom-mocha.js:106

TypeError: Cannot read property 'path' of null
    at atom-text-editor.atomMochaRunTestFileFromEditor (/Users/valentin/.atom/packages/atom-mocha/lib/atom-mocha.js:106:78)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -0:30.6.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
     -0:28.8.0 core:close (atom-text-editor.editor.mini.is-focused)
     -0:26.3.0 atom-mocha:runTestFileFromEditor (atom-text-editor.editor.is-focused)
  2x -0:12 atom-mocha:toggle (atom-text-editor.editor.is-focused)
     -0:00.6.0 atom-mocha:runTestFileFromEditor (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-mocha, v0.0.4
emmet, v2.4.3
file-icons, v1.7.9
linter, v1.11.4
livereload, v0.4.4
wakatime, v5.0.8

# Dev
No dev packages
```

**Comment by boogie666** [comment]
sry this took so incredably long to fix :(, i've been busy. i couldn't reproduce this problem, but i've added some guard at the point of the problem and atom-mocha should not crash anymore. the problem is that you were running a non existing file. the 'Run Test (Current File)' command should run the currently open file so if you had nothing open that might cause a crash... but i can't make it happen on my machine.
